// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvvNjbsi51_nH1Kc_6O9snlEoVon97GPw',
    appId: '1:824476788160:web:181976bcfafa154af55425',
    messagingSenderId: '824476788160',
    projectId: 'brain-boost-8821a',
    authDomain: 'brain-boost-8821a.firebaseapp.com',
    databaseURL: 'https://brain-boost-8821a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brain-boost-8821a.firebasestorage.app',
    measurementId: 'G-4S4T4N90HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqnAPOPTF5Ym8O6w66UBv5k3qzzPjo58A',
    appId: '1:824476788160:android:ecf77d18c7c0a5b9f55425',
    messagingSenderId: '824476788160',
    projectId: 'brain-boost-8821a',
    authDomain: 'brain-boost-8821a.firebaseapp.com',
    databaseURL: 'https://brain-boost-8821a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brain-boost-8821a.firebasestorage.app',
  );
}
